### ISSUE TITLE
Fully Automatic

### ISSUE THREAD

**Issue by Andy-ABTec** [Andy-ABTec/minimal-mistakes#5]
@MarkSummerville, I note you've included a "Fully Automatic" block in the feature row of the splash screen.

I'm guessing you had something in mind to go here. I know you can get TV Rename to monitor the "download" folders for new matching files and automate the move/copy (at least I think that's how it works!)

Is there anything else that should go here - Sorry, I don't use this feature - persuade me otherwise...

**Comment by MarkSummerville** [comment]
HI,

I have to be honest I didn't put that much thought into the 3 features we should showcase. Happy for other's opinions.

Yes I was getting at the look at a folder and decide all the copying/donwloading/creating that needs to be done to knock the files into order. Further that the app can monitor the folder, be run from CLI  on a timer.

The 3 tiles were just intended to be teasers to really highlight why people would bother with TVR rather than another tool. Free/Flexible/FullyAutomatic were the 3 that popped into my head straight  away. Maybe something like 'works with Kodi' would be more appropriate? 

Interested to hear other's thoughts.

**Comment by Andy-ABTec** [comment]
NO, I'm much happier with the original idea, I was just wondering if there was some functionality I'd totally missed re automation. 
Flexible, Fully Automatic and ??? - don't think free is a particularly good hook?

**Comment by MarkSummerville** [comment]
I'm planning to put a timer into the code to you can make it run a scan/action events every 24 hours which will add to this concept.

I think 'free' is a pretty good reason to use it. It's one of the first things mentioned on the Kodi equivalent https://kodi.tv/about

**Comment by Andy-ABTec** [comment]
Likely to be in V3?
Just to confirm is the software GPL2 GPL3 or MIT License?

**Comment by MarkSummerville** [comment]
Yeah - should be

GPL 3: https://github.com/TV-Rename/tvrename/blob/master/LICENSE.md
